core/account/urls.py
from django.urls import path
from account import views

app_name = 'account'
urlpatterns = [
    path('', views.login_index, name='login_index'),
    path('login/create', views.login_index, name='create_account'),
    path('logout', views.logout_account, name='logout_account'),
]

core/app/urls.py
from django.urls import path
from app import views

app_name = 'app'
urlpatterns = [
    path('index/', views.index, name='app_index'),
    path('video/', views.video, name='app_video'),
    path('channel/', views.channel, name='app_channel'),
    path('video/list/', views.video_list, name='app_video_list'),
    #path('channel/sort/', views.channel, name='video_sort'),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
	path('account/', include('account.urls')),
	path('app/', include('app.urls')),
]

core/account/models.py
from django.db import models

# Create your models here.

core/app/models.py
from django.db import models
from django.contrib.auth.models import User

class Video(models.Model):
    class Meta:
        db_table = 'videos'

    id = models.CharField(max_length=255, primary_key=True)
    title = models.CharField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    
    def __str__(self):
        return self.title

core/app/forms.py
from django import forms


class VideoIdForm(forms.Form):
    video_id = forms.CharField(label='動画ID')

class ChannelIdForm(forms.Form):
    channel_id = forms.CharField(label='チャンネルID')

class SortChoiceForm(forms.Form):
	CHOICE = (
		('published', '公開日付'),
		('title', 'タイトル'),
		('view_count', '視聴回数'),
		('like_count', '高評価数'),
		('dislike_count', '低評価数'),
		('like_percent', '高評価率'),
	)

	sort = forms.fields.ChoiceField(required=True,
									choices=CHOICE,
									initial=['published'],
									widget=forms.widgets.Select(attrs={
										'class': 'round',
										'placeholder': 'Sort'
									}))

core/account/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, logout, authenticate
from django.views.generic import CreateView, View, TemplateView
from django.contrib.auth.models import User


class LoginIndexView(TemplateView):
	template_name = 'account/index.html'

login_index = LoginIndexView.as_view()


def logout_account(request):
    logout(request)
    print(request,"Logged out,please come back again.")
    return redirect('account:login_index')

core/app/views.py
from django.shortcuts import render
from app.db import MySQLClient
from django.views.generic import TemplateView, ListView
from app.videos import YoutubeAPIClient
from app.forms import VideoIdForm, ChannelIdForm, SortChoiceForm
from django.contrib.auth.models import User
from app.models import Video


class IndexView(TemplateView):
    template_name = 'app/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['video_id_form'] = VideoIdForm()
        context['channel_id_form'] = ChannelIdForm()
        return context

index = IndexView.as_view()


class VideoView(TemplateView):
    template_name = 'app/video.html'

    def post(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        form = VideoIdForm(data=request.POST)
        if form.is_valid():
            video_id = form.cleaned_data.get('video_id')

        context['video_data'] = YoutubeAPIClient().get_video_data(video_id)
        return self.render_to_response(context)

video = VideoView.as_view()


class ChannelView(TemplateView):
    template_name = 'app/channel.html'

    def post(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        form = ChannelIdForm(data=request.POST)
        if form.is_valid():
            channel_id = form.cleaned_data.get('channel_id')

        context['videos'] = YoutubeAPIClient().get_video_datas_from_channel(channel_id)
        context['sort_form'] = SortChoiceForm()


        for d in context['videos']:
            u = User.objects.filter(username='klein').first()
            print('型：', type(u))
            Video(id=d.get('video_id'), title=d.get('title'), user=u).save()



        return self.render_to_response(context)
    

channel = ChannelView.as_view()


class VideoListView(ListView):
    template_name = 'app/video_list.html'
    model = Video
    context_object_name = 'videos'

    """
    def post(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        form = ChannelIdForm(data=request.POST)
        if form.is_valid():
            channel_id = form.cleaned_data.get('channel_id')

        context['videos'] = YoutubeAPIClient(os.environ.get('YOUTUBE_API_KEY')).get_video_datas_from_channel(channel_id)
        context['sort_form'] = SortChoiceForm()

        return self.render_to_response(context)
    """
video_list = VideoListView.as_view()

core/app/templates/app/channel.html
{% extends "app/base.html" %}

{% block content %}
<h3 class="text-center my-4">取得結果</h3>

<table class="table table-striped table-bordered">
    <thead>
        <tr class="text-center">
            <th scope="col">タイトル</th>
            <th scope="col">公開日付</th>
            <th scope="col">視聴回数</th>
            <th scope="col">高評価数</th>
            <th scope="col">低評価数</th>
            <th scope="col">高評価率</th>
        </tr>
    </thead>
    <tbody class="text-center">
        {% for video in videos %}
            <tr>
            <th scope="row">{{ video.title }}</th>
            <td>{{ video.published }}</td>
            <td>{{ video.view_count }}</td>
            <td>{{ video.like_count }}</td>
            <td>{{ video.dislike_count }}</td>
            <td>{{ video.like_percent }}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock content %}

core/app/templates/app/index.html
{% extends "app/base.html" %}

{% block content %}
<h3 class="text-center my-4">Youtube動画情報取得</h3>
<!--
<table class="table table-striped table-bordered">
    <thead>
        <tr class="text-center">
            <th scope="col">名前</th>
            <th scope="col">性別</th>
            <th scope="col">年齢</th>
        </tr>
    </thead>
    <tbody class="text-center">
        {% for user in users %}
        <tr>
        <th scope="row">{{ user.name }}</th>
        <td>{{ user.gender_str }}</td>
        <td>{{ user.age }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
-->
<div class="form-group">
    <form action="{% url 'app:app_video' %}" method="POST">
        {% csrf_token %}
        {{ video_id_form }}
        <input type="submit" value="取得する">
    </form>
</div>
<div class="form-group">
    <form action="{% url 'app:app_channel' %}" method="POST">
        {% csrf_token %}
        {{ channel_id_form }}
        <input type="submit" value="取得する">
    </form>
</div>

{% endblock content %}

core/app/templates/app/video.html
{% extends "app/base.html" %}

{% block content %}
<h3 class="text-center my-4">取得結果</h3>
<table class="table table-striped table-bordered">
    <thead>
        <tr class="text-center">
            <th scope="col">タイトル</th>
            <th scope="col">視聴回数</th>
            <th scope="col">高評価数</th>
            <th scope="col">低評価数</th>
            <th scope="col">高評価率</th>
        </tr>
    </thead>
    <tbody class="text-center">
        <tr>
        <th scope="row">{{ video_data.title }}</th>
        <td>{{ video_data.view_count }}</td>
        <td>{{ video_data.like_count }}</td>
        <td>{{ video_data.dislike_count }}</td>
        <td>{{ video_data.like_percent }}</td>
        </tr>
    </tbody>
</table>

{% endblock content %}

core/app/templates/app/video_list.html
{% extends "app/base.html" %}

{% block content %}
<h3 class="text-center my-4">一覧</h3>

<ul>
    {% for item in videos %}
        <li>{{ item }}</li>
    {% endfor %}
</ul>

{% endblock content %}